version: 2

builds:
  - id: neeto-cli-gen
    dir: gen
    main: ./cmd/neeto-cli-gen/
    binary: neeto-cli-gen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/neetozone/neeto-cli-commons/gen/version.Version={{.Version}}
      - -X github.com/neetozone/neeto-cli-commons/gen/version.Commit={{.ShortCommit}}
      - -X github.com/neetozone/neeto-cli-commons/gen/version.Date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "neeto-cli-gen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  name_template: "v{{ .Version }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
