version: v1.0

fail_fast: true

plan: pro

paths:
  - "**/*.go"
  - "**/*.tmpl"
  - "**/testdata/**"
  - "**/go.mod"
  - "**/go.sum"
  - assets/**
  - .neetoci/**

machine_type: multi

commands:
  - checkout
  - neetoci-version go 1.26
  - export GOPRIVATE=github.com/neetozone/*
  - git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
  - go mod download
  - gofmt -l . | tee /tmp/fmt_output && test ! -s /tmp/fmt_output
  - go vet ./...
  - go test ./...
  - (cd gen && go mod download && gofmt -l . | tee /tmp/gen_fmt_output && test ! -s /tmp/gen_fmt_output)
  - (cd gen && go vet ./...)
  - (cd gen && go test ./...)

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
